server.port: 8080
management.port: 8081
management.context-path: /manage

security.basic.enabled: false

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/taller
  username: sboot
  password: secreto